#!/bin/bash
code --install-extension ambar.bundle-size
code --install-extension antfu.browse-lite
code --install-extension ArunagiriTM.material-ui
code --install-extension asvetliakov.vscode-neovim
code --install-extension bradlc.vscode-tailwindcss
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension esafirm.kotlin-formatter
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension fwcd.kotlin
code --install-extension GitHub.copilot
code --install-extension GitHub.copilot-chat
code --install-extension jsayol.firebase-explorer
code --install-extension kosz78.nim
code --install-extension mathiasfrohlich.Kotlin
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension msjsdiag.vscode-react-native
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.prisma
code --install-extension ritwickdey.LiveServer
code --install-extension vincaslt.highlight-matching-tag
code --install-extension WallabyJs.console-ninja
code --install-extension wix.glean
code --install-extension Wscats.eno
code --install-extension xabikos.JavaScriptSnippets